In [130]:
print("Hello World")

Hello World


# My First Class

In [131]:
print(2)

2


In [132]:
print(type(2))

<class 'int'>


In [133]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [134]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [135]:
import pandas as pd

In [136]:
import numpy as np

# Arrays

In [137]:
#creating arrays
a=np.array([1,2,3,4,5])
print(a)
a
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [138]:
a.ndim

1

In [139]:
#Two Dimensional Array
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [140]:
b.ndim

2

# numpy arrays using zeros and ones function

In [141]:
array1=np.zeros(10,dtype=int) 
array1.reshape(2,5)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [142]:
array2=np.zeros((2,5),int)
array2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [143]:
array3=np.ones(4)
array3

array([1., 1., 1., 1.])

In [144]:
array3=np.ones((4,3),int)
array3

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [145]:
array3=np.ones((3,4,5),dtype=int)
array3

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

# Array Functions

In [146]:
var=np.array([22,44,56])
var

array([22, 44, 56])

In [147]:
var.argmin()  #Gives the min element index value from the array

0

In [148]:
var.argmax() #Gives the max element index value from the array

2

In [149]:
var.dtype

dtype('int32')

In [150]:
var.dtype.name

'int32'

In [84]:
#indexing
var[2]

56

In [85]:
#Slicing
var[0:3]

array([22, 44, 56])

In [86]:
var[0:2]

array([22, 44])

In [87]:
#list
lst=[2,3,5]
lst

[2, 3, 5]

In [88]:
print(type(lst))

<class 'list'>


In [89]:
lst[0]=100
lst

[100, 3, 5]

In [90]:
var

array([22, 44, 56])

In [91]:
var[0]=10000
var

array([10000,    44,    56])

# reshape and resize

In [92]:
d=np.arange(12)
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [93]:
d.reshape(2,6)


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [94]:
d.min()

0

In [95]:
d.max()

11

In [96]:
d.sum()

66

In [97]:
print(type(d))

<class 'numpy.ndarray'>


In [98]:
d.ndim

1

In [99]:
q=56780
q

56780

In [100]:
np.sqrt(q)


238.2855429941145

In [101]:
np.log(q)

10.946939430026962

# Series

In [102]:
s=pd.Series(np.random.random(5))
s

0    0.952406
1    0.450209
2    0.927782
3    0.126995
4    0.531478
dtype: float64

In [103]:
s[0] #Indexing

0.9524055976687864

In [104]:
s[1] #Slicing

0.4502085019560429

In [105]:
s[0:5]

0    0.952406
1    0.450209
2    0.927782
3    0.126995
4    0.531478
dtype: float64

In [106]:
s[0:3]

0    0.952406
1    0.450209
2    0.927782
dtype: float64

In [107]:
#changing the index value of series
s.index=['a','b','c','d','e']
s

a    0.952406
b    0.450209
c    0.927782
d    0.126995
e    0.531478
dtype: float64

In [108]:
s=pd.Series(np.random.random(5),index=['a','b','c','d','e'])
s

a    0.503112
b    0.926769
c    0.300640
d    0.443800
e    0.431115
dtype: float64

In [109]:
#Pulling the max value with index number

In [110]:
s.argmax()

1

In [111]:
s.argmin()

2

In [112]:
s[0]

0.5031124942150943

In [113]:
s.min()

0.30063958596205287

In [114]:
s.max()

0.9267694476039555

# Data Frames

In [115]:
s1=pd.Series(np.random.random(4))
s2=pd.Series(np.random.random(4))
s1,s2

(0    0.449813
 1    0.173991
 2    0.445000
 3    0.561231
 dtype: float64,
 0    0.239348
 1    0.116501
 2    0.881560
 3    0.249113
 dtype: float64)

In [116]:
#converting series to data frame
a=pd.DataFrame([s1,s2])
a

0         1        2         3
0  0.449813  0.173991  0.44500  0.561231
1  0.239348  0.116501  0.88156  0.249113

In [117]:
#Creating dictionary and Converting to DataFrame
dct={'Name':['Divya','Gresh','Khyathi','Tulasi'],'Age':[18,17,21,20]}
dct

{'Name': ['Divya', 'Gresh', 'Khyathi', 'Tulasi'], 'Age': [18, 17, 21, 20]}

In [118]:
type(dct)

dict

In [119]:
import pandas as pd
D=pd.DataFrame(dct)
D

Name  Age
0    Divya   18
1    Gresh   17
2  Khyathi   21
3   Tulasi   20

In [120]:
type(D)

pandas.core.frame.DataFrame

In [121]:
D['Gender']=['male','Female','Male','Male']
D

Name  Age  Gender
0    Divya   18    male
1    Gresh   17  Female
2  Khyathi   21    Male
3   Tulasi   20    Male

In [122]:
#Converting List to DataFrames
A=[1,2,3,4]
B=['Ajay','Rahul','Rohan','Prachaith']
pd.DataFrame([A,B])

0      1      2          3
0     1      2      3          4
1  Ajay  Rahul  Rohan  Prachaith

In [123]:
D['Gender']=['Male','Female','Male','Female']
D

Name  Age  Gender
0    Divya   18    Male
1    Gresh   17  Female
2  Khyathi   21    Male
3   Tulasi   20  Female